import assert from 'node:assert/strict';
import { resumoPeriodo } from '../src/lib/relatorios/metricas.ts';
const periodo = { inicio: '2026-01-01', fim: '2026-01-31' };
const vendas = [{ data: '2026-01-01', bruta: 100, desconto: 10, taxaMarketplace: 5, cpv: 20, quantidade: 1 }];
const devolucoes = [{ id: 'd', data: '2026-01-02', valorTotal: 30, quantidade: 1, custoExtra: 7 }];
const resumo = resumoPeriodo(vendas, [{ data: '2026-01-01', valor: 3 }], periodo, devolucoes);
assert.equal(resumo.bruta, 70);
assert.equal(resumo.quantidade, 0);
assert.equal(resumo.receita, 60);
assert.equal(resumo.receitaLiquidaGerencial, 55);
assert.equal(resumo.despesasTotal, 10);
assert.equal(resumo.resultado, 25);
assert.equal(resumo.custoExtraDevolucoes, 7);
assert.equal(resumoPeriodo(vendas, [], periodo, [{ ...devolucoes[0], custoExtra: undefined }]).resultado, 35);
assert.equal(resumoPeriodo(vendas, [], periodo, [{ ...devolucoes[0], data: '2026-02-01' }]).resultado, 65);
console.log('OK: devolução, taxas e custos extras subtraídos uma única vez, custo opcional e competência.');
const integral = resumoPeriodo([{ ...vendas[0], desconto: 0 }], [], periodo, [{ ...devolucoes[0], valorTotal: 100 }]);
assert.equal(integral.bruta, 0);
assert.equal(integral.receita, 0);
assert.equal(integral.quantidade, 0);
assert.equal(integral.receitaLiquidaGerencial, -5);
